### ISSUE TITLE
Ajout de librairies pour l'install

### ISSUE THREAD

**Issue by Gis70** [AuFilElec/remora_soft#11]
Bonjour,

Il faut installer la librairie ArduinoJson et installer le dernière version en RC de ESP8266 en mettant le lien [https://github.com/esp8266/Arduino/releases/download/2.4.0-rc1/package_esp8266com_index.json](url) pour obtenir getCommand()

A rajouter dans le readme :)

**Comment by Azema** [comment]
Salut @Gis70 ,

Effectivement,en prenant les sources de mon dépôt Github, il vous faut la bibliothèque **ArduinoJson**. Mais cela ne concerne que les sources de mon dépôt, pour le moment. Une Pull Request pour le readme serait sympa ;-)

Si vous ne souhaitez pas être embêté, je vous invite à prendre la dernière relaease du dépôt de Charles-Henri Hallard, à savoir la [version v1.3.4](https://github.com/hallard/remora_soft/releases/tag/v1.3.4) en ce moment.

**Comment by Azema** [comment]
Ajouté dans le README

**Comment by Gis70** [comment]
Bonjour j'avais oublié ça : https://github.com/esp8266/Arduino/releases/tag/2.4.0-rc1
;) (avec l'install via le manager de carte)

**Comment by Azema** [comment]
Salut @Gis70 , si tu veux faire une PR pour mettre à jour le README, ça me convient :)

**Comment by Gis70** [comment]
OK, je m'en charge ;)

**Comment by Azema** [comment]
Salut @Gis70 , avec les dev que je réalise sur la version [**dev-2.0**](https://github.com/AuFilElec/remora_soft/tree/dev-2.0), il ne devrait plus y avoir ce genre de problème. Car j'utilise _platformio_ au lieu de l'IDE Arduino, et platformio gère les dépendances.
