### ISSUE TITLE
Info de connection Wifi non prise en compte sur page web

### ISSUE THREAD

**Issue by Gis70** [AuFilElec/remora_soft#15]
Bonjour,

Les informations de connections à un réseau wifi ne sont pas prises en comptes si elles sont spécifiées en dur dans le code et que l'on veut les modifier via l'interface web. 

version de Remora : V1.3.6

**Comment by Azema** [comment]
Salut @Gis70 ,

Effectivement, la configuration de la connexion WiFi vérifie si les variables **DEFAULT_WIFI_SSID** et **DEFAULT_WIFI_PASS** sont définies (https://github.com/hallard/remora_soft/blob/63fe8ac630b3d7d762cc3bed2a9c43bc7acb89ae/remora_soft.ino#L208). Sinon, elle check si les infos sont stockées dans la config (https://github.com/hallard/remora_soft/blob/63fe8ac630b3d7d762cc3bed2a9c43bc7acb89ae/remora_soft.ino#L217).

Il est nécessaire de ne pas mettre les infos en dur dans le code, en plus, c'est un peu plus sécurisé pour le réseau WiFi. Utilise plutôt la config via l'interface Web ou bien tu as peut être une proposition d'évolution.

**Comment by Gis70** [comment]
Salut, non c'est de ma faute, je n'ai pas regardé le code et c'est moi qui l'avais rentré comme ça à l'époque. Le code est cohérent. As tu une version a tester stable (plus récente que ma v1.3.6 qui fonctionne très bien)  ? Merci

**Comment by Azema** [comment]
Non, pour le moment, la version en cours est la 1.3.6.

Plusieurs évolutions sont en attente de relecture et de validation sur le dépôt de Charles. Tu peux les voir dans les PR (https://github.com/hallard/remora_soft/pulls)

Si tu as des propositions d'évolutions, n'hésites pas à créer un ticket.
